### ISSUE TITLE
Tweens don't test play in parallel for animation resource

### ISSUE THREAD

**Issue by spigelli** [KoBeWi/Godot-Tween-Suite#2]

**Comment by KoBeWi** [comment]
`parallel` has no effect when animation is assigned, it's even set to readonly if you use animation (though maybe hiding it would be more clear).
If you use TweenAnimations, the parallel animations are set up in the editor as part of a single step.

**Comment by GLukaz** [comment]
I was planning to make a massive use of this plugin, but it's true, doesn't run in parallel even if you set as parts of single steps. Please can you check?

**Comment by KoBeWi** [comment]
Fixed in d714f9b8f369edc4caee6de9320223b12411c773
I forgot to test parallel animations and they turned out broken. I would've noticed and fixed it much sooner if the issue had more details than only a title.
