### ISSUE TITLE
[Suggestion] Accept node metadata in tween editor

### ISSUE THREAD

**Issue by cpazzra** [KoBeWi/Godot-Tween-Suite#4]
Maybe this is possible currently, but wasn't able to see anything the docs.

Seems like it would be incredibly powerful if supported. Tried poking around under the hood but couldn't quite make heads or tails of how these text fields are parsed.

![image](https://github.com/KoBeWi/Godot-Tween-Suite/assets/6466091/9d329949-b95a-4338-a670-444f29ee0420)

![image](https://github.com/KoBeWi/Godot-Tween-Suite/assets/6466091/7d75b8af-b667-4e1e-92ee-83cebeff7a6d)

**Comment by KoBeWi** [comment]
Value fields use Expression, so you can't call methods.
I could add a special syntax though.

**Comment by KoBeWi** [comment]
Implemented in 27c1a607b037d03d671850dfa6cd6ddc34defd67
See https://github.com/KoBeWi/Godot-Tween-Suite?tab=readme-ov-file#value-fields for info.
